module.exports = {
  ADD_TODO: 'ADD_TODO',
  FETCHED_POMODOROS: 'FETCHED_POMODOROS',
  FETCHED_TASKS: 'FETCHED_TASKS',
  FETCH_POMODOROS: 'FETCH_POMODOROS',
  FETCH_TASKS: 'FETCH_TASKS',
  POMODORO_FINISHED: 'POMODORO_FINISHED',
  TOGGLE_DONE: 'TOGGLE_DONE',
};
